[package]
name = "light-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
sdl2 = "0.35.2"
light = {path = "../light/"}
rayon = "1.7.0"
ultraviolet = "0.9.1"
